version: "3"
services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: qui.help.db
        environment:
            SA_PASSWORD: Password12!
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
